### ISSUE TITLE
[EPIC] Expose options for k3k nodes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#13]
There are multiple options that should be supported for exposing the clusters including:

**- in-cluster service (enabled by default)** 
**- loadbalancer service (enabled via expose.loadbalancer.enabled)** 
```
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: loadbalancer-example
  namespace: default
spec:
  servers: 2
  agents: 3
  token: test
  version: v1.26.0-k3s2
  expose:
    loadbalancer:
      enabled: true
```

**- ingress**
```
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: ingress-example
  namespace: default
spec:
  servers: 2
  agents: 3
  token: test
  version: v1.26.0-k3s2
  expose:
    ingress:
      enabled: true
      ingressClassName: "nginx"
``` 

For Ingress expose k3k needs to support multiple options including:
- ingress class name
- auto configuration for ssl passthrough for multiple ingress controllers

**Comment by rossella** [comment]
@galal-hussein please add validation steps.

**Comment by galal-hussein** [comment]
To validate the issue:

- Using nodePort

using the cli, there is no extra steps needed, just create the cluster:

a nodePort service should be created with the name:

```
k3k-<cluster-name>-service
```
In the same namespace of the cluster

- Using ingress nginx

To expose the cluster using the ingress, you need to create a cluster object with the following spec:

```
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: ingress-example
  namespace: default
spec:
  servers: 1
  expose:
    ingress:
      ingressClassName: "nginx"
```

An ingress should be created with the same name as the service that will expose the cluster api

**Comment by ShylajaDevadiga** [comment]
### Validated using k3kcli version 
Created a cluster object using the above spec 
```
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: ingress-example
  namespace: default
spec:
  servers: 1
  expose:
    ingress:
      ingressClassName: "nginx"
```
Deployed service ad deployment as below
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
```
Deployed an ingress resource

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nginx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
```

Verified nginx welcome page is displayed from the local node
```
➜  ~ curl -H "Host: nginx.local" http://<PUBLIC IP REDACTED>
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to 
```

**Comment by ShylajaDevadiga** [comment]
Not deploying ingress or nginx service and just applying the cluster object I am seeing issues with ingress not getting created.
Created cluster as below
```
k3kcli cluster create --kubeconfig /etc/rancher/rke2/rke2.yaml --namespace k3k-system --servers 1 --mode shared --server-args="--tls-san=<PUBLIC IP>" k3kcluster
```
Deployed below cluster object 
```
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: ingress-example
  namespace: default
spec:
  servers: 1
  expose:
    ingress:
      ingressClassName: "nginx"
```
```
ec2-user@ip-172-31-23-203:~> kubectl get nodes
NAME                                          STATUS   ROLES                       AGE   VERSION
ip-172-31-23-203.us-east-2.compute.internal   Ready    control-plane,etcd,master   13h   v1.33.2+rke2r1
ec2-user@ip-172-31-23-203:~> kubectl get pods -A
NAMESPACE            NAME                                                                   READY   STATUS      RESTARTS   AGE
default              k3k-ingress-example-kubelet-z7422                                      1/1     Running     0          3m12s
default              k3k-ingress-example-server-0                                           1/1     Running     0          3m12s
k3k-system           coredns-5688667fd4-s4bng-kube-system-k3kcluster-636f72656-c6e37        1/1     Running     0          4m7s
k3k-system           k3k-7489bcb69f-6cc6m                                                   1/1     Running     0          6m45s
k3k-system           k3k-k3kcluster-kubelet-5h6ts                                           1/1     Running     0          5m45s
k3k-system           k3k-k3kcluster-server-0                                                1/1     Running     0          5m46s
kube-system          cloud-controller-manager-ip-172-31-23-203.us-east-2.compute.internal   1/1     Running     0          13h
kube-system          etcd-ip-172-31-23-203.us-east-2.compute.internal                       1/1     Running     0          13h
kube-system          helm-install-rke2-canal-pmssd                                          0/1     Completed   0          13h
kube-system          helm-install-rke2-coredns-x5fst                                        0/1     Completed   0          13h
kube-system          helm-install-rke2-ingress-nginx-wcv95                                  0/1     Completed   0          13h
kube-system          helm-install-rke2-metrics-server-4vks8                                 0/1     Completed   0          13h
kube-system          helm-install-rke2-runtimeclasses-vnz7f                                 0/1     Completed   0          13h
kube-system          helm-install-rke2-snapshot-controller-crd-qdvhh                        0/1     Completed   0          13h
kube-system          helm-install-rke2-snapshot-controller-hvsv4                            0/1     Completed   1          13h
kube-system          kube-apiserver-ip-172-31-23-203.us-east-2.compute.internal             1/1     Running     0          13h
kube-system          kube-controller-manager-ip-172-31-23-203.us-east-2.compute.internal    1/1     Running     0          13h
kube-system          kube-proxy-ip-172-31-23-203.us-east-2.compute.internal                 1/1     Running     0          13h
kube-system          kube-scheduler-ip-172-31-23-203.us-east-2.compute.internal             1/1     Running     0          13h
kube-system          rke2-canal-8k5fp                                                       2/2     Running     0          13h
kube-system          rke2-coredns-rke2-coredns-65dc69968-6nk88                              1/1     Running     0          13h
kube-system          rke2-coredns-rke2-coredns-autoscaler-68d5f76f7-cddhp                   1/1     Running     0          13h
kube-system          rke2-ingress-nginx-controller-2wcd7                                    1/1     Running     0          13h
kube-system          rke2-metrics-server-7c74688658-b9k9w                                   1/1     Running     0          13h
kube-system          rke2-snapshot-controller-696989ffdd-kphzf                              1/1     Running     0          13h
local-path-storage   local-path-provisioner-7c8666cb46-ft6fq                                1/1     Running     0          7m12s
ec2-user@ip-172-31-23-203:~> 
```
Ingress was not created
```
ec2-user@ip-172-31-23-203:~> kubectl get ingressclass -A
NAME    CONTROLLER             PARAMETERS   AGE
nginx   k8s.io/ingress-nginx   <none>       13h
ec2-user@ip-172-31-23-203:~> kubectl get ingress -A
No resources found
ec2-user@ip-172-31-23-203:~> kubectl get svc -A
NAMESPACE     NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
default       k3k-ingress-example-kube-dns              ClusterIP   10.43.12.164    <none>        53/UDP,53/TCP,9153/TCP         3m45s
default       k3k-ingress-example-kubelet               ClusterIP   10.43.82.240    <none>        10250/TCP,9443/TCP             3m45s
default       k3k-ingress-example-service               ClusterIP   10.43.40.103    <none>        443/TCP,2379/TCP               3m45s
default       k3k-ingress-example-service-headless      ClusterIP   None            <none>        443/TCP,2379/TCP               3m45s
default       kubernetes                                ClusterIP   10.43.0.1       <none>        443/TCP                        13h
k3k-system    k3k-k3kcluster-kube-dns                   ClusterIP   10.43.213.183   <none>        53/UDP,53/TCP,9153/TCP         6m19s
k3k-system    k3k-k3kcluster-kubelet                    ClusterIP   10.43.168.244   <none>        10250/TCP,9443/TCP             6m19s
k3k-system    k3k-k3kcluster-service                    NodePort    10.43.232.145   <none>        443:31330/TCP,2379:30137/TCP   6m19s
k3k-system    k3k-k3kcluster-service-headless           ClusterIP   None            <none>        443/TCP,2379/TCP               6m19s
k3k-system    k3k-webhook                               ClusterIP   10.43.215.53    <none>        443/TCP                        7m18s
kube-system   rke2-coredns-rke2-coredns                 ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP                  13h
kube-system   rke2-ingress-nginx-controller-admission   ClusterIP   10.43.164.50    <none>        443/TCP                        13h
kube-system   rke2-metrics-server                       ClusterIP   10.43.61.240    <none>        443/TCP                        13h
ec2-user@ip-172-31-23-203:~> 
```
