### ISSUE TITLE
Feature Request: User defined container runtime

### ISSUE THREAD

**Issue by Citrullin** [rancher/k3k#134]
It would be an interesting feature to have the ability to use a different container runtimes than the default one.

I may have a look into this myself eventually.

**Comment by caroline-suse-rancher** [comment]
This may be a larger k3s integration/request, as it's not currently strictly supported on k3s. This may need a Jira ticket and for @jp-gouin to evaluate.

**Comment by Citrullin** [comment]
> This may be a larger k3s integration/request, as it's not currently strictly supported on k3s. This may need a Jira ticket and for [@jp-gouin](https://github.com/jp-gouin) to evaluate.

Hey, thanks for the response on this. We realized that k3s is not a solution for embedded environment any way. So, this became somewhat not as relevant for us. It still certainly might be useful for other environments where you may want to spawn some k3s cluster with kata containers to simulate devices or isolate more.

**Comment by aganesh-suse** [comment]
@galal-hussein Please advice if testing what is mentioned in description here: https://github.com/rancher/k3k/issues/582 covers the testing for this issue also. Is there anything in addition that needs to be tested here? Thanks.

**Comment by galal-hussein** [comment]
Yes it should cover this issue as well

**Comment by ShylajaDevadiga** [comment]
@galal-hussein In that case, It would be helpful if you could provide the validation steps.

**Comment by galal-hussein** [comment]
@ShylajaDevadiga will do

**Comment by galal-hussein** [comment]
## Validation Template

Context: https://github.com/rancher/k3k/pull/742

## Feature description

This feature allows the users to specify alternative `RuntimeClass` and `SecurityContext` other than the defaults.

## What was fixed, or what change have occurred

A new Cluster Spec fields have been added:

1. cluster.Spec.RuntimeClassName
2. cluster.Spec.SecurityContext

## Areas or cases that should be tested

### 1. Normal cluster creation

Since this is a new field, we should validation that cluster creation with default options has no regrssion

### 2. Running a cluster with different runtimeclass

#### Prepare the host clutser
1- Install k3s host cluster
2- install `crun` runtime from the [official release pages](https://github.com/containers/crun/releases/tag/1.27)
3- Rename the binary to `crun` and move it to /usr/local/bin
4- restart k3s
5- verify that k3s auto detected the crun runtime, you should see the following lines in `/var/lib/rancher/k3s/agent/etc/containerd/config.toml`

```toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."crun"]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."crun".options]
  BinaryName = "/usr/local/bin/crun"
  SystemdCgroup = true
```

#### Run virtual cluster with the new runtime

6- Install k3k controller via helm chart
7- Create a new cluster with an alternative runtime class
```yaml
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: cruncluster
  namespace: test-x
spec:
  runtimeClassName: crun
  agents: 0
  expose:
    nodePort: {}
  mode: virtual
  persistence:
    storageRequestSize: 2G
    type: dynamic
  servers: 1
  sync:
    configMaps:
      enabled: true
    ingresses:
      enabled: false
    persistentVolumeClaims:
      enabled: true
    priorityClasses:
      enabled: false
    secrets:
      enabled: true
    services:
      enabled: true
    storageClasses:
      enabled: false
  tlsSANs:
  - <IP-of-host-server>
```

The virtual mode should come up successfully and server pod should be ready, after that you can use the k3kcli kubeconfig generate to generate a kubeconfig for the cluster and make sure its working as expected:

```sh
➜  k3kcli kubeconfig generate --name cruncluster --namespace test-x 
INFO[0000] waiting for cluster to be available..        
INFO[0000] certificate CN=system:admin,O=system:masters signed by CN=k3s-client-ca@1776373605: notBefore=2026-04-16 20:06:45 +0000 UTC notAfter=2027-04-16 21:09:01 +0000 UTC 
INFO[0000] You can start using the cluster with:

	export KUBECONFIG=/home/hussein/go/src/github.com/rancher/k3k/test-x-cruncluster-kubeconfig.yaml
	kubectl cluster-info
	 
➜   export KUBECONFIG=/home/hussein/go/src/github.com/rancher/k3k/test-x-cruncluster-kubeconfig.yaml
        kubectl cluster-info
Kubernetes control plane is running at https://192.168.1.221:31141
CoreDNS is running at https://192.168.1.221:31141/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://192.168.1.221:31141/api/v1/namespaces/kube-system/services/https:metrics-server:https/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by aganesh-suse** [comment]
k3s version v1.35.4+k3s1 - 1 server setup. 
Ubuntu OS

## Steps followed: 
1. did `sudo apt install crun`
2. got the crun binary https://github.com/containers/crun/releases/download/1.27/crun-1.27-linux-amd64 and renamed to `crun` pushed it to `/usr/local/bin`
```
$ crun --version
crun version 1.27
commit: a718a92cc9a94955a5a550b6fdec1378c247ec50
rundir: /run/user/1000/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJLpushed the toml file :
```
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config-v3.toml.d/crun.toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."crun"]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."crun".options]
  BinaryName = "/usr/local/bin/crun"
  SystemdCgroup = truerestarted k3s.
```
3. restart k3s.
4. create/apply runtimeclass crun:
```
$ cat runtimeclass.yaml
apiVersion: node.k8s.io/v1
handler: crun
kind: RuntimeClass
metadata:
  name: crun
```
5. Verify crun works: installed a regular pod with crun runtimeclass:
```
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  runtimeClassName: crun
  hostUsers: false
  containers:
  - name: ubuntu2204
    image: ubuntu:22.04
    command: ["sleep", "40000000000"]
  restartPolicy: Never
```
```
$ kubectl get pods -n default
NAME     READY   STATUS    RESTARTS   AGE
ubuntu   1/1     Running   0          10m
```
6. when i apply the virtual cluster yaml:
```
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: virthpfalse
  namespace: k3k-system
spec:
  version: v1.35.4-k3s1
  serverLimit:
    memory: 3Gi
  hostUsers: false
  securityContext:
    privileged: false
  runtimeClassName: crun
  mode: virtual
  persistence:
    storageRequestSize: 2G
    type: dynamic
  servers: 1
  agents: 1
  sync:
    configMaps:
      enabled: true
    ingresses:
      enabled: false
    persistentVolumeClaims:
      enabled: true
    priorityClasses:
      enabled: false
    secrets:
      enabled: true
    services:
      enabled: true
    storageClasses:
      enabled: false
  tlsSANs:
  - TLS_SAN_ADDRESS
```
7. Observation: 
cluster creation seems to have failed: 
```
$ k3kcli cluster list
NAMESPACE    NAME          MODE      STATUS   POLICY
k3k-system   virthpfalse   virtual   Failed   <none>
```
```
$ kubectl get all -n k3k-system
NAME                                         READY   STATUS    RESTARTS   AGE
pod/k3k-6f8588d68b-tlqnz                     1/1     Running   0          14m
pod/k3k-virthpfalse-agent-854bfcddf7-gnhhh   1/1     Running   0          7m41s
pod/k3k-virthpfalse-server-0                 1/1     Running   0          7m41s

NAME                                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)            AGE
service/k3k-virthpfalse-service            ClusterIP   10.43.229.102   <none>        443/TCP,2379/TCP   7m41s
service/k3k-virthpfalse-service-headless   ClusterIP   None            <none>        443/TCP,2379/TCP   7m41s

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/k3k                     1/1     1            1           14m
deployment.apps/k3k-virthpfalse-agent   1/1     1            1           7m41s

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/k3k-6f8588d68b                     1         1         1       14m
replicaset.apps/k3k-virthpfalse-agent-854bfcddf7   1         1         1       7m41s

NAME                                      READY   AGE
statefulset.apps/k3k-virthpfalse-server   1/1     7m41s
```
generate the kubeconfig file: 
```
$ k3kcli kubeconfig generate --name virthpfalse --namespace k3k-system
INFO[0000] waiting for cluster to be available..
INFO[0000] certificate CN=system:admin,O=system:masters signed by CN=k3s-client-ca@1777500237: notBefore=2026-04-29 21:03:57 +0000 UTC notAfter=2027-04-29 22:12:17 +0000 UTC
INFO[0000] You can start using the cluster with:

	export KUBECONFIG=/home/ubuntu/k3k-system-virthpfalse-kubeconfig.yaml
	kubectl cluster-info
```
node/pod status of k3k cluster: 
```
$ alias kctlk3k="/usr/local/bin/kubectl --kubeconfig /home/ubuntu/k3k-system-virthpfalse-kubeconfig.yaml"
$ kctlk3k get nodes
E0429 22:12:52.258220   24218 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: the server is currently unable to handle the request"
$ kctlk3k get pods -A
E0429 22:12:57.430679   24241 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: the server is currently unable to handle the request"
```
Have i missed something vital in the crun installation? 
Or is this an issue?
