### ISSUE TITLE
[EPIC]Support multiple nodes (agents) in shared mode

### ISSUE THREAD

**Issue by jp-gouin** [rancher/k3k#167]
Currently the `virtual-kubelet` register a single node in the virtual cluster.
This would impact application using `affinity. For example, pod running on separate nodes won't be scheduled  

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app-affinity
  template:
    metadata:
      labels:
        app: sample-app-affinity
    spec:
      containers:
        - name: sample-container
          image: nginx
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sample-app-affinity
              topologyKey: "kubernetes.io/hostname"
```
