### ISSUE TITLE
Incorrect `server` field in kubeconfig when running K3k on RKE2

### ISSUE THREAD

**Issue by kingsd041** [rancher/k3k#267]
#### **Environment**  
- **K3k Version**: `v0.3.0`  
- **RKE2 Version**: 
```
 hailong  ~  k get nodes
NAME      STATUS   ROLES                              AGE   VERSION
prime-2   Ready    control-plane,etcd,master,worker   35d   v1.31.3+rke2r1
prime-3   Ready    control-plane,etcd,master,worker   23d   v1.31.3+rke2r1
prime-4   Ready    control-plane,etcd,master,worker   23d   v1.31.3+rke2r1
```
- **Rancher Version**: `2.10.1`  
- **Installation Method**: Rancher-managed custom cluster  
- **K3k Deployment Method**: Running K3k on RKE2  

#### **Description**  
When running K3k on an RKE2 cluster created via Rancher, the generated kubeconfig contains an incorrect `server` field. Instead of pointing to the K3k API server, it uses the Rancher UI URL, making it impossible to connect to the K3k cluster using the kubeconfig.  

#### **Steps to Reproduce**  
1. Deploy an RKE2 cluster via Rancher (custom cluster).  
2. Install and start a K3k cluster on RKE2.  
3. Generate the kubeconfig using:  
   ```sh
   k3kcli kubeconfig generate --name <cluster-name>
   ```  
4. Inspect the kubeconfig file.  

#### **Expected Behavior**  
The `server` field in the kubeconfig should point to the K3k API server’s actual endpoint, allowing direct access to the cluster.  

#### **Actual Behavior**  
The kubeconfig contains the Rancher UI URL:  
```yaml
server: https://10.201.170.114.sslip.io:30108
```  
This prevents direct access to the K3k cluster.  

#### **Additional Information**  
- The RKE2 cluster is managed by Rancher, and the Rancher server is accessible at:  
  `https://10.201.170.114.sslip.io/`  
- This issue may be related to how K3k determines the API server address when running on an RKE2 cluster managed by Rancher.  

#### **Suggested Fix**  
K3k should properly detect and use the correct API server address when running on RKE2, instead of defaulting to the Rancher UI URL.  

KUBECONFIG:
```
cat /Users/ksd/k3k-10-kubeconfig.yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTkRBek5qTTRNREF3SGhjTk1qVXdNakkwTURJeU16SXdXaGNOTXpVd01qSXlNREl5TXpJdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTkRBek5qTTRNREF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRak00alJ0MXZBaXArZlFPUk9vNWJUS2ZNcG1QQnpLTG41Y21qNnZmWHgKNHBORXNuOXpNaDBTS1NFMTFVbDQwTTNmN0tFbTd1SFNrc2JzZmhXSlhIZWdvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWMzTmRMdlhKeE9GdzdHS2NUMlAvClh6bDNjSFF3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU5wSEtWWnpqVm5BV0oyWjlHWjVUWlY2aVQwZFFXSFMKdHgyRERIRmg0d3c0QWlFQXNaUTVGWll4SFlNb2t1cFdLdWhqcWlRc1B3ZmF3TXdJa240NzJEU0pCRVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://10.201.170.114.sslip.io:30108
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJUkZlK2hxS25qMzR3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelF3TXpZek9EQXdNQjRYRFRJMU1ESXlOREF5TWpNeU1Gb1hEVEkyTURJeApOVEF5TXpJek9Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFdTVFbGRqTDdrU0dJQmQKQXdkdEVYSVhUdkJPaFc5cjdkK2k1emdHVU5JNjJRcjRiMXhTZm9WaS9ZR0JNQlNiaGFUK2k5MXRaRWNnT3Z4NgpQZDlYaDF5alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVHVOb3NxYUJxRjJiN21kTG11NlRpTmxtWkl2ekFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBNGdBNHRZdjdCMzUyYUNFZnd2a1FORzBPNEhaaTV1U3czOCtvcnZoVzhSUUlnRWdIOVZwM25LL1FhN3FibQoyZjk2UThYbE5aZnd6RUFXYkxWd1dqVTJsVU09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTkRBek5qTTRNREF3SGhjTk1qVXdNakkwTURJeU16SXdXaGNOTXpVd01qSXlNREl5TXpJdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTkRBek5qTTRNREF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRWlBwMTRmN2NVUElQb1IwbWJvVk1xc1lESXlJb2Q2Q2I0TmhOQ1VLRjUKZ2JMZU1obWdYcFVRYVdvdkFGalVPN01SVmFDUzIrS0JYb2owRWRQSUdMb29vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTdqYUxLbWdhaGRtKzVuUzVydWs0CmpaWm1TTDh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU5ITTZjeGNoVE1aTTN5WVpmbjI3U2xNUGpLMXFadm0KRXpvTFhDdFFIRXZQQWlCeGMvN2lmbkFnN1VnY3hYM3VKTkZ4dWhlVVpoRUkyM3JjWXRnUmhrQ0pkQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVA3V3laYVV2cG9ubWtkbGsza1JpclRzVzN4cksvWGVxbHFjWjJGVGt1dTlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUzdrU1YyTXZ1UklZZ0YwREIyMFJjaGRPOEU2RmIydnQzNkxuT0FaUTBqclpDdmh2WEZKKwpoV0w5Z1lFd0ZKdUZwUDZMM1cxa1J5QTYvSG85MzFlSFhBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```
