### ISSUE TITLE
`clusterLimit.workerLimit` does not take effect in virtual mode

### ISSUE THREAD

**Issue by kingsd041** [rancher/k3k#286]
**Description:**  

When creating a K3s cluster using the `virtual` mode in K3k, the `clusterLimit` settings only apply to the K3s server but do not take effect for K3s agents.  

### **Steps to Reproduce**  

1. Deploy a K3k cluster with the following configuration:  

```yaml
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: k3k-2
  namespace: k3k-test
spec:
  mode: virtual
  servers: 1
  agents: 2
  clusterCIDR: 10.42.0.0/16
  serviceCIDR: 10.43.0.0/16
  clusterDNS: 10.43.0.10
  clusterLimit:
    serverLimit:
      cpu: "2"
      memory: "4Gi"
    workerLimit:
      cpu: "1"
      memory: "2Gi"
```

2. After the cluster is successfully created, check the applied resource limits.  
3. The K3s server has the correct resource limits:  
```
~# kubectl get pod k3k-k3k-2-server-0 -n k3k-test -o=jsonpath='{.spec.containers[*].resources}'
{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}}
```
4. However, the K3s agents do not reflect the `workerLimit` settings.  
```
~# kubectl get pod k3k-k3k-2-agent-fd9477c8c-4dvp6 -n k3k-test -o=jsonpath='{.spec.containers[*].resources}'
{}
```

### **Expected Behavior**  
- Both K3s server and agents should respect the resource limits defined in `clusterLimit`.  
- The K3s agent should have the following resource limits applied:  

```yaml
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
```

### **Actual Behavior**  
- The K3s server has the correct resource limits.  
- The K3s agents do not follow the `workerLimit` settings.  

### **Environment:**  
- K3k version: `v0.3.0`
