### ISSUE TITLE
PVC Status Shows as Pending in k3k Cluster While It Is Bound in Local K3s Cluster

### ISSUE THREAD

**Issue by kingsd041** [rancher/k3k#289]
**Environmental Info:**
Host Cluster Version: v1.31.5+k3s1

Node(s) CPU architecture, OS, and Version:  ubuntu 22.04

Host Cluster Configuration: 1 server

K3K Cluster Configuration: 1 server

I encountered an issue where a PVC in a k3k-created "shared" cluster remains in a `Pending` state, even though it is correctly bound in the underlying local K3s cluster.  
**Describe the bug:**

**Steps To Reproduce:**
- Created a cluster with `k3k create`: 
1. Deploy a local K3s cluster and use it to run k3k.  
2. Create a "shared" type k3s cluster using k3k:  
   ```sh
   k3kcli cluster create --namespace k3k-test k-1 
   ```  
3. Deploy an Nginx application in the k-1 cluster, using a PVC backed by the local K3s cluster’s `local-path` storage:  

   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: nginx-deployment
   spec:
     replicas: 2
     selector:
       matchLabels:
         app: nginx
     template:
       metadata:
         labels:
           app: nginx
       spec:
         containers:
           - name: nginx
             image: registry.cn-hangzhou.aliyuncs.com/kingsd/nginx:install-tools
             ports:
               - containerPort: 80
             volumeMounts:
               - name: nginx-storage
                 mountPath: /usr/share/nginx/html
         volumes:
           - name: nginx-storage
             persistentVolumeClaim:
               claimName: nginx-deployment-pvc
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: nginx-deployment-pvc
   spec:
     accessModes:
       - ReadWriteOnce
     resources:
       requests:
         storage: 1Gi
   ```

4. Check the PVC status in the k-1 cluster:  

   ```sh
   kubectl get pvc
   ```

   Output:
   ```
   NAME                   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
   nginx-deployment-pvc   Pending                                                     <unset>                 3h22m
   ```

5. Check PVs in the k-1 cluster:  
   ```sh
   kubectl get pv
   ```
   Output:
   ```
   No resources found
   ```

6. However, checking the local K3s cluster shows the PVC and PV are correctly bound:  

   ```sh
   kubectl get pvc -A
   ```
   Output:
   ```
   NAMESPACE   NAME                                                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
   k3k-test    nginx-deployment-pvc-default-k-1-6e67696e782d6465706c6f79-f8d10   Bound    pvc-3b12c3d4-c36d-47d4-a332-ca5d9e953fa0   1Gi        RWO            local-path     <unset>                 3h24m
   ```

   ```sh
   kubectl get pv
   ```
   Output:
   ```
   NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                      STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
   pvc-3b12c3d4-c36d-47d4-a332-ca5d9e953fa0   1Gi        RWO            Delete           Bound    k3k-test/nginx-deployment-pvc-default-k-1-6e67696e782d6465706c6f79-f8d10   local-path     <unset>                          3h25m
   ```

**Expected behavior:**

The PVC in the k-1 cluster should correctly reflect the `Bound` status, as it is already bound in the local K3s cluster.  

**Actual behavior:**

- The PVC remains in `Pending` state in the k-1 cluster, even though it is actually bound in the local K3s cluster.  
- No PV resources are visible when querying in the k-1 cluster.  
**Additional context / logs:**
- It seems that k3k does not correctly reflect the PVC status from the local K3s cluster.  
- Any insights on how PVC binding is supposed to work in a k3k "shared" cluster would be appreciated.
