### ISSUE TITLE
[Shared Mode] Resources limits for ClusterSets

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#292]
In shared mode:

- All virtual cluster under the same clusterset workloads run within the same namespace on the host cluster.
- When a limit is specified to clusterset, Resourcequota object will be applied to that namespace to limit the total resources consumed by virtual clusters.
- The limit should include the same limits specified in Resource quota object for example:
  - cpu
  - memory
  - pods

**Comment by VestigeJ** [comment]
I don't think this should be in to test yet - I don't see the field yet on the api to specify the resource limits through the clustersets. Unless this was meant to be passed in through to the maxLimits map? Would be good to have some more validation steps on these issues.

$ helm ls -n k3k-system
```
NAME	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART       	APP VERSION
k3k 	k3k-system	1       	2025-04-04 22:43:58.447776953 +0000 UTC	deployed	k3k-0.3.1-r2	v0.3.1
```

$ k explain clusterset.spec

```
GROUP:      k3k.io
KIND:       ClusterSet
VERSION:    v1alpha1

FIELD: spec <Object>


DESCRIPTION:
    Spec defines the desired state of the ClusterSet.

FIELDS:
  allowedNodeTypes	<[]string>
    AllowedNodeTypes specifies the allowed cluster provisioning modes. Defaults
    to [shared].

  defaultLimits	<Object>
    DefaultLimits specifies the default resource limits for servers/agents when
    a cluster in the set doesn't provide any.

  defaultNodeSelector	<map[string]string>
    DefaultNodeSelector specifies the node selector that applies to all clusters
    (server + agent) in the set.

  defaultPriorityClass	<string>
    DefaultPriorityClass specifies the priorityClassName applied to all pods of
    all clusters in the set.

  disableNetworkPolicy	<boolean>
    DisableNetworkPolicy indicates whether to disable the creation of a default
    network policy for cluster isolation.

  maxLimits	<map[string]Object>
    MaxLimits specifies the maximum resource limits that apply to all clusters
    (server + agent) in the set.

  podSecurityAdmissionLevel	<string>
  enum: privileged, baseline, restricted
    PodSecurityAdmissionLevel specifies the pod security admission level applied
    to the pods in the namespace.
```

$ k explain clusterset.spec.defaultLimits

```
GROUP:      k3k.io
KIND:       ClusterSet
VERSION:    v1alpha1

FIELD: defaultLimits <Object>


DESCRIPTION:
    DefaultLimits specifies the default resource limits for servers/agents when
    a cluster in the set doesn't provide any.

FIELDS:
  serverLimit	<map[string]Object>
    ServerLimit specifies resource limits for server nodes.

  workerLimit	<map[string]Object>
    WorkerLimit specifies resource limits for agent nodes.
```


$ k explain clusterset.spec.maxLimits

```
GROUP:      k3k.io
KIND:       ClusterSet
VERSION:    v1alpha1

FIELD: maxLimits <map[string]Object>


DESCRIPTION:
    MaxLimits specifies the maximum resource limits that apply to all clusters
    (server + agent) in the set.
```

**Comment by VestigeJ** [comment]
@enrichman thanks for explaining that - I'd like to get the development charts onto the --devel listed entries and the early adopters onto the regular charts soon then. I wasn't aware they were using the developer listed charts for their deployments.

**Comment by VestigeJ** [comment]
I'd close this as completed, but I'm unable to do so.


$ helm ls -n k3k-system

```
NAME          	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
k3k-1744307741	k3k-system	1       	2025-04-10 17:55:42.257298657 +0000 UTC	deployed	k3k-0.3.2-rc1	v0.3.2-rc1
```

$ k3kcli --version

```
k3kcli Version: v0.3.2-rc1
```

$ cat cset2.yaml

```
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: default
  namespace: csetlimits
spec:
  displayName: resourcelimits
  disableNetworkPolicy: false
  allowedModeTypes:
  - "shared"
  podSecurityAdmissionLevel: "baseline"
  defaultPriorityClass: "default-priority"
  quota:
    hard:
      cpu: "10"
      memory: "1G"
      pods: "3"
```

$  k describe quota -n csetlimits

```
Name:       k3k-default
Namespace:  csetlimits
Resource    Used  Hard
--------    ----  ----
cpu         0     10
memory      0     1G
pods        0     3
```

$ cat pod-resource.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: high-priority
  namespace: csetlimits
spec:
  containers:
  - name: high-priority
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "10Gi"
        cpu: "500m"
      limits:
        memory: "10Gi"
        cpu: "500m"
  priorityClassName: system-cluster-critical
```

Yay pod rejected for resources 🟢 

$ k create -f pod-resource.yaml

```
Error from server (Forbidden): error when creating "pod-resource.yaml": pods "high-priority" is forbidden: exceeded quota: k3k-default, requested: memory=10Gi, used: memory=0, limited: memory=1G
```

🟢 lower resource reqs deploys

$ k create -f low-resource.yaml

```
pod/default-priority created
```

$ cat low-resource.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: default-priority
  namespace: csetlimits
spec:
  containers:
  - name: default-priority
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "250Mi"
        cpu: "9"
      limits:
        memory: "250Mi"
        cpu: "9"
  priorityClassName: default-priority
```

$ kg quota -n csetlimits

```
NAME          AGE     REQUEST                                  LIMIT
k3k-default   8m22s   cpu: 9/10, memory: 250Mi/1G, pods: 1/3
```

🟢 Deployments requesting too many resources of either cpu/memory/or pod counts were all correctly rejected for deployment into the namespace.

$ k create -f adjacent.yaml

```
Error from server (Forbidden): error when creating "adjacent.yaml": pods "low-priority" is forbidden: exceeded quota: k3k-default, requested: memory=750Mi, used: memory=250Mi, limited: memory=1G
```

$ k create -f adjacent.yaml
```
Error from server (Forbidden): error when creating "adjacent.yaml": pods "low-priority" is forbidden: exceeded quota: k3k-default, requested: cpu=2,memory=750Mi, used: cpu=9,memory=250Mi, limited: cpu=10,memory=1G

$ kg quota -n csetlimits

```
NAME          AGE   REQUEST                                   LIMIT
k3k-default   10m   cpu: 10/10, memory: 500Mi/1G, pods: 2/3
```

$ kg quota -n csetlimits

```
NAME          AGE   REQUEST                                  LIMIT
k3k-default   12m   cpu: 4/10, memory: 500Mi/1G, pods: 2/3
```
