### ISSUE TITLE
[Shared Mode] Add NodeSelectors to ClusterSets

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#295]
In shared mode, the user should specify a default node selector to be applied to each cluster in that clusterset.

**Comment by VestigeJ** [comment]
Hey Hussein would a good validation process for this to be a multi-node RKE2 host cluster, create a clusterset with the defaultNodeSelector predetermined. Then create a k3k cluster use the clusterset defaultNodeSelector to direct the created cluster towards a specific worker in the host cluster?

**Comment by enrichman** [comment]
@VestigeJ that would be perfect 👍

**Comment by VestigeJ** [comment]
So far with cilium this isn't looking very good. 


$ helm ls -n k3k-system

```
NAME          	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
k3k-1744307741	k3k-system	1       	2025-04-10 17:55:42.257298657 +0000 UTC	deployed	k3k-0.3.2-rc1	v0.3.2-rc1
```

$ k3kcli --version

```
k3kcli Version: v0.3.2-rc1
```

Originally created the clusterset using the below file, the three servers did start up correctly on the right node ie 172-31-26-151. I then edited the existing clusterset in place to point to 172-31-16-201 and watched the progress. The agents never came up as healthy and the servers eventually got stuck in the broken state being partially on two different nodes.

$ cat cset.yaml

```
cat cset.yaml
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: default
  namespace: shared
spec:
  displayName: newnametoseeinoutputs
  disableNetworkPolicy: false
  allowedModeTypes:
  - "shared"
  podSecurityAdmissionLevel: "baseline"
  defaultPriorityClass: "default-priority"
  defaultNodeSelector:
    kubernetes.io/hostname: ip-172-31-26-151
```

$ kg clusterset default -n shared -o yaml

```
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  creationTimestamp: "2025-04-10T18:07:41Z"
  generation: 2
  name: default
  namespace: shared
  resourceVersion: "20048"
  uid: e3791c94-50ba-4af3-ab19-dea74ea6fc1d
spec:
  allowedModeTypes:
  - shared
  defaultNodeSelector:
    kubernetes.io/hostname: ip-172-31-16-201
  defaultPriorityClass: default-priority
  disableNetworkPolicy: false
  displayName: newnametoseeinoutputs
  podSecurityAdmissionLevel: baseline
```

![Image](https://github.com/user-attachments/assets/4caf0288-dcf5-43b0-96ad-824b0a12b544)

**Comment by galal-hussein** [comment]
Validation steps:

- Create a host cluster with at least 2 nodes
- Deploy k3k helm package
- Create a new namespace and new priorityClass

```
kubectl create ns test
kubectl create priorityclass testpc
```

- On the host cluster make sure to have a clusterSet with both priority class and nodeSelector:
```
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: clusterset-example
  namespace: test
spec:
  defaultNodeSelector:
    kubernetes.io/hostname: ubuntu2404-1
  defaultPriorityClass: testpc
```

where the label  `kubernetes.io/hostname: ubuntu2404-1` represents one of the node names on the host cluster.

- Create a cluster in the same namespace `test`
```
# k3kcli cluster create --namespace test --mode shared --persistence-type ephemeral testcluster
```

All pods created related to the testcluster should be deployed on the node `ubuntu2404-1` with priorityclass `testpc`, also the virtual cluster should have only one node.
