### ISSUE TITLE
serverArgs with datastore-endpoint

### ISSUE THREAD

**Issue by Negashev** [rancher/k3k#304]
I tried to run k3s (in k3k) on postgres)

**Environmental Info:**
Host Cluster Version: 
rke2 version v1.31.6+rke2r1

Node(s) CPU architecture, OS, and Version: 
Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-92-generic x86_64) 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Host Cluster Configuration:
RKE2 cilium 1 ALL + 3 worker (2cpu 4gb 20ssd)

K3K Cluster Configuration:
```
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: single-ssssss
  namespace: default
spec:
  agents: 1
  clusterCIDR: 10.30.0.0/16
  clusterDNS: 10.31.0.10
  mode: shared
  persistence:
    type: ephemeral
  serverArgs:
    - "--write-kubeconfig-mode=777"
    - "--datastore-endpoint=postgres://postgres:passw0rd@postgres-k3s.default.svc.cluster.local:5432/k3s?sslmode=disable"
  servers: 1
  serviceCIDR: 10.31.0.0/16
  version: v1.32.2-k3s1
```

**Describe the bug:**
master say:
time="2025-03-12T19:10:54Z" level=warning msg="Received HTTP bootstrap request from 10.42.1.35:58602, but embedded etcd is not enabled."
time="2025-03-12T19:10:54Z" level=error msg="Sending HTTP/1.1 400 response to 10.42.1.35:58602: etcd disabled"
(run without restart infinity)

agent say:
{"level":"info","timestamp":"2025-03-12T19:04:57.709Z","msg":"decoded bootstrap"}
{"level":"fatal","timestamp":"2025-03-12T19:04:57.709Z","msg":"failed to create new virtual kubelet instance","error":"data does not contain a valid RSA or ECDSA private key"}
(restart infinity)

**Steps To Reproduce:**
apply cluster.yaml 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

[k3k-5dc6bdc8df-8r874_k3k.log](https://github.com/user-attachments/files/19216187/k3k-5dc6bdc8df-8r874_k3k.log)

[k3k-single-ssssss-server-0_k3k-single-ssssss-server.log](https://github.com/user-attachments/files/19216189/k3k-single-ssssss-server-0_k3k-single-ssssss-server.log)

[k3k-single-ssssss-kubelet-t57vn_k3k-single-ssssss-kubelet.log](https://github.com/user-attachments/files/19216191/k3k-single-ssssss-kubelet-t57vn_k3k-single-ssssss-kubelet.log)

[postgres-k3s-56d4f96959-jfwj7_postgres.log](https://github.com/user-attachments/files/19216192/postgres-k3s-56d4f96959-jfwj7_postgres.log)

<img width="935" alt="Image" src="https://github.com/user-attachments/assets/76de2c65-4784-4703-a86a-50d7ef6eaaac" />

repeat on 0.2.0, 0.3.0, 0.3.1-rc

**Comment by jp-gouin** [comment]
Hi @Negashev thanks for the issue. 
At the moment changing the datastore is not supported. K3k, for the bootstrap process, rely on K3s APIs that only exist when ETCD is enable. 

We are going to consider this feature in the future. 
I'm curious, why dom't you want to use ETCD ?

**Comment by Negashev** [comment]
Hello, I just want to store data in Postgresql, It's easier to work with him

**Comment by rossella** [comment]
In order to make this happen we'd need Kine but it's not integrated in k3k yet. We'll look at it in the future.

**Comment by pandvan** [comment]
We are very interested in this feature as it could lead to k3k adoption for us.

**Comment by dasarinaidu** [comment]
@galal-hussein Can you add validation plan for this card? Thanks

**Comment by dasarinaidu** [comment]
**Observation 1 : spec.datastore is ignored by the K3k controller during reconciliation.**

**Reproduction Steps:**
	1.	Patch CRD or install build containing spec.datastore schema.
	2.	Create a Cluster CR specifying an external PostgreSQL datastore endpoint under spec.datastore.endpoint.
	3.	Wait for k3k-virtual-pg-cluster-server-0 to reach Running.
	4.	Inspect external PostgreSQL database and server pod logs.

**Expected Behavior**
K3s server starts with --datastore-endpoint pointing to PostgreSQL, creates the Kine schema, and populates tables in k3s_external.

**Actual Behavior**
	1.	PostgreSQL database remains completely empty (no relations created).
	2.	Server pod logs confirm embedded etcd initialization:
```
level=info msg="Managed etcd cluster initializing"
level=info msg="Running kube-apiserver ... --etcd-servers=https://127.0.0.1:2379 --storage-backend=etcd3"
```

**Comment by galal-hussein** [comment]
## Validation Template

Context: https://github.com/rancher/k3k/pull/879

## What was fixed, or what change have occurred

K3k now supports an external datastore (kine) for virtual clusters. The feature relies on `secretMounts` to mount the **external database** configuration into the server pods at cluster creation time. There is **no dedicated CRD field for the external datastore**: the datastore is configured by mounting a k3s drop-in config secret into both the init and the server config directories.

## Areas or cases that should be tested

Virtual cluster creation with external datastores such as MySQL, PostgreSQL, or external etcd.

### Test Cases

#### 1. Single server, shared mode, external PostgreSQL

Deploy a PostgreSQL instance reachable from the host cluster. It can also be deployed as a pod, for example:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: test-k3k
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14 
          env:
            - name: POSTGRES_PASSWORD
              value: "password" 
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: test-k3k
spec:
  clusterIP: None 
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: test-k3k
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
```

Then create the `datastore-config` secret and the cluster as shown below:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: datastore-config
  namespace: test-k3k
type: Opaque
stringData:
  config.yaml: |
    datastore-endpoint: postgres://postgres:password@postgres:5432/k3k
    cluster-init: false
    server: ""
---
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: test
  namespace: test-k3k
spec:
  mode: shared
  servers: 1
  secretMounts:
    - name: externaldb-init-config
      secretName: datastore-config
      mountPath: /opt/rancher/k3s/init/config.yaml.d/
      role: server
    - name: externaldb-server-config
      secretName: datastore-config
      mountPath: /opt/rancher/k3s/server/config.yaml.d/
```

- Check that the cluster comes up successfully, and that the `k3k` database is populated when querying PostgreSQL.
- Check that no server pod carries the `etcdpod.k3k.io/finalizer` finalizer.

#### 2. Single server, virtual mode, external PostgreSQL

Same as case 1, but with `mode: virtual`.

#### 3. HA servers on external datastore

Same as case 1, but with 3 servers.

#### 4. Regression: embedded etcd unchanged (default path)

**Comment by dasarinaidu** [comment]
**Observation 2 — External datastore via spec.serverArgs fails to provision (works via spec.secretMounts)**

**Environment:** Host: RKE2 v1.36.2+rke2r1 (Rancher downstream dastest1) · K3K controller 1.2.0-rc3 · external PostgreSQL 15.

**Summary:** When the external datastore endpoint is supplied through spec.serverArgs (--datastore-endpoint=…), the cluster never reaches Ready even though the k3s server successfully connects to the external database. Supplying the same endpoint through spec.secretMounts (k3s config drop-in) provisions to Ready normally. Only the delivery method differs.

**Steps to reproduce:**

1. Deploy an external PostgreSQL reachable from the host cluster.
2. Create two shared-mode clusters, each pointed at its own database:
3. Cluster A (serverArgs):

yaml
```
     spec:
       mode: shared
       servers: 1
       serverArgs:
         - "--datastore-endpoint=postgres://postgres:passw0rd@postgres-k3s.datastore.svc.cluster.local:5432/k3sa?sslmode=disable"
```
4. Cluster B (secretMounts): same endpoint (db k3sb) delivered as a k3s drop-in via a Secret mounted at /etc/rancher/k3s/config.yaml.d/.
Watch both provision: kubectl get clusters -n <ns>.

**Actual result:**

1. Cluster B → Ready. Server 1/1 Running, kine schema present in the external DB, workloads schedule.
2. Cluster A → Failed. The k3s server does connect to the DB (log shows Configuring pgx database connection pooling → Database tables and indexes are up to date → Kine available; the DB accumulates >1000 kine rows), but the K3K controller then fails:

  **status:** ProvisioningFailed: failed executing '/v1-k3s/server-bootstrap' request to k3s server: status code: 400 Bad Request
  **kubelet:** unable to decode bootstrap: secrets "k3k-<cluster>-kubeconfig" not found  →  CrashLoopBackOff

/v1-k3s/server-bootstrap is disabled in external-datastore mode, so the controller should skip it (as it does for Cluster B) — but on the serverArgs path it still calls it, gets 400, never creates the k3k-<cluster>-kubeconfig bootstrap secret, and the virtual kubelet crashloops.

**Expected result:** External datastore configured via serverArgs should provision to Ready, same as via secretMounts — or, if serverArgs is intentionally unsupported for the datastore, the controller should reject it / document it rather than reaching Failed.


**Question for dev:** Is external datastore via serverArgs intended to be supported, or is secretMounts (drop-in config) the only supported path? If the former, this is a defect in the controller's ClusterInit detection on the serverArgs path.
