### ISSUE TITLE
Update an applied cluster config

### ISSUE THREAD

**Issue by BroderPeters** [rancher/k3k#311]
I was wondering whether I'm able to update an already applied and running cluster config, to e.g. change the `serverArgs` later on.
Did I maybe miss part of the docs for this?

What I've tried so far:

1. Initially applied a cluster like this
```yaml
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: capsule
  namespace: capsule
spec:
  mode: virtual
```
2. Then later wanted to switch the CNI setup accordingly

```yaml
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: capsule
  namespace: capsule
spec:
  mode: virtual
  serverArgs:
  - --flannel-backend=none
  - --disable-network-policy
  - --disable=traefik
```
3. Restarted the k3k server statefulset

That didn't seem to work out and I'm going through the error logs just now to figure out whether it is connected to my change, or whether restarting generally isn't a good idea.

Is there currently a way to do this? Or doesn't this make change at all?
In a "real" cluster setup I might also want to switch some fundamental cluster configs.
