### ISSUE TITLE
ClusterSet commands in `k3kcli`

### ISSUE THREAD

**Issue by enrichman** [rancher/k3k#317]
The `k3kcli` should implement at least the `clusterset create` and `clusterset delete` commands.

Disclaimer: #316 still needs to be merged.

To implement the ClusterSet is a singleton it has a fixed `default` name. The argument used in the commands will be then used to create the appropriate namespace and/or used as the human readable name (`displayName`). Like the Clusters a dedicated namespace with the `k3k-` prefix will be used.

Examples:

### no flags

```
k3kcli clusterset create myclusterset
```

The `name` argument is used both to create (or match) the namespace, and the displayName:

```yaml
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: default
  namespace: k3k-myclusterset
spec:
  displayName: myclusterset
```

### `--namespace`

```
k3kcli clusterset create --namespace another myclusterset
```

If the `--namespace` flag is specified the ClusterSet will be created in that namespace, and the `name` argument is used in the displayName:

```yaml
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: default
  namespace: another
spec:
  displayName: myclusterset
```

### `--display-name`

```
k3kcli clusterset create --display-name myname myclusterset
```

If the `--display-name` flag is specified the ClusterSet will be created with that `displayName`, and the `name` argument is used to match the right namespace (`k3k-myclusterset` in this case):

```yaml
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: default
  namespace: k3k-myclusterset
spec:
  displayName: myname
```

### `--namespace` and `--display-name`

```
k3kcli clusterset create --namespace another --display-name myname myclusterset
```

If both the flags are specified then the argument name is ignored. The `--display-name` flag will be used in the `displayName`, and the `--namespace` flag will be used to match the right namespace:

```yaml
apiVersion: k3k.io/v1alpha1
kind: ClusterSet
metadata:
  name: default
  namespace: another
spec:
  displayName: myname
```

We could eventually add a warning log about this behavior.

## Cluster

The Cluster commands can be improved adding the `--clusterset` flag. The behavior will be the same of the ClusterSet.

If a Cluster is being created with the `--clusterset` flag then a new ClusterSet within the `k3k-<CLUSTERSET_NAME>` namespace will be created.

If the `--namespace` and the `--clusterset` flag are both specified, then the namespace will be the one of the `--namespace` flag, and the ClusterSet will be created with the `displayName` specified within the `--clusterset` flag.

We should log the user if the ClusterSet was already there, and we should fail to create the ClusterSet if in the namespace there are already running Clusters.
