### ISSUE TITLE
DownwardAPI volumes are not being updated on pod updates

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#334]
**Environmental Info:**
Host Cluster Version: 

v1.32.3+k3s1
Node(s) CPU architecture, OS, and Version: 

1 node ubuntu 24.04

Host Cluster Configuration:

1 server

K3K Cluster Configuration:

1 server shared mode

**Describe the bug:**

In shared mode when you create a pod with downward api volume annotation, and then update the pod's annotation the volume will not be updated.

**Steps To Reproduce:**
- Created a cluster with `k3k create`: 
```
k3kcli cluster create --namespace shared --mode shared --servers 1 sharedcluster
```
- create a pod with downwardAPI volume in the virtual cluster
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    foo: bar
spec:
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: "annotaions"
        fieldRef:
          fieldPath: metadata.annotations
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: downward
      mountPath: /opt/annotations
```
- exec to the pod and make sure that annotation file does have foo bar annotation
```
root@test-pod:/# cat /opt/annotations/annotaions 
foo="bar"
k3k.io/name="test-pod"
k3k.io/namespace="default"
kubectl.kubernetes.io/last-applied-configuration="{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{\"foo\":\"bar\"},\"name\":\"test-pod\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"image\":\"nginx:latest\",\"name\":\"nginx\",\"volumeMounts\":[{\"mountPath\":\"/opt/annotations\",\"name\":\"downward\"}]}],\"volumes\":[{\"downwardAPI\":{\"items\":[{\"fieldRef\":{\"fieldPath\":\"metadata.annotations\"},\"path\":\"annotaions\"}]},\"name\":\"downward\"}]}}\n"
kubernetes.io/config.seen="2025-04-29T09:44:07.951891663Z"
```
- update the annotations in the pod and add `foo2: bar2`

**Expected behavior:**

you should see the file is updated in /opt/annotations/annotations with the new annotation

**Actual behavior:**

the file is not updated

**Additional context / logs:**

**Comment by ShylajaDevadiga** [comment]
### Validated using k3k version 0.3.2
```
k3kcli --version
k3kcli Version: v0.3.2
```
Created k3k cluster in shared mode on single node k3k cluster
```
k3kcli cluster create --namespace shared --mode shared --servers 1 sharedcluster
```
Created a pod with downwardAPI volume in the virtual cluster
```
ec2-user@ip-172-31-16-141:~> kubectl apply -f testpod 
pod/test-pod configured

ec2-user@ip-172-31-16-141:~> kubectl exec -it test-pod  -- bash
root@test-pod:/# cat /opt/annotations/annotaions |grep foo --color
foo="bar"
kubectl.kubernetes.io/last-applied-configuration="{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{\"foo\":\"bar\"},\"name\":\"test-pod\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"image\":\"nginx:latest\",\"name\":\"nginx\",\"volumeMounts\":[{\"mountPath\":\"/opt/annotations\",\"name\":\"downward\"}]}],\"volumes\":[{\"downwardAPI\":{\"items\":[{\"fieldRef\":{\"fieldPath\":\"metadata.annotations\"},\"path\":\"annotaions\"}]},\"name\":\"downward\"}]}}\n"
root@test-pod:/# 
```
Updated annotation with foo2:bar2 and applied the changes
```
ec2-user@ip-172-31-16-141:~> cat testpod
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    foo2: bar2
spec:
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: "annotaions"
        fieldRef:
          fieldPath: metadata.annotations
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: downward
      mountPath: /opt/annotations
```
Validated the new annotations are updated
```
ec2-user@ip-172-31-16-141:~> kubectl apply -f testpod 
pod/test-pod configured
ec2-user@ip-172-31-16-141:~> kubectl exec -it test-pod  -- bash
root@test-pod:/# cat /opt/annotations/annotaions |grep foo --color
foo2="bar2"
kubectl.kubernetes.io/last-applied-configuration="{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{\"foo2\":\"bar2\"},\"name\":\"test-pod\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"image\":\"nginx:latest\",\"name\":\"nginx\",\"volumeMounts\":[{\"mountPath\":\"/opt/annotations\",\"name\":\"downward\"}]}],\"volumes\":[{\"downwardAPI\":{\"items\":[{\"fieldRef\":{\"fieldPath\":\"metadata.annotations\"},\"path\":\"annotaions\"}]},\"name\":\"downward\"}]}}\n"
```
