### ISSUE TITLE
k3k-kubelet should provide default cpu/memory limit if downward API is used

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#337]
**Environmental Info:**
Host Cluster Version: 

v1.32.3+k3s1
Node(s) CPU architecture, OS, and Version: 

1 node ubuntu 24.04

Host Cluster Configuration:

1 server

K3K Cluster Configuration:

1 server shared mode

**Describe the bug:**

When downward API for resource limits for cpu/memory is used, it should get a default value, this is standard behavior for k8s upstream

**Steps To Reproduce:**
- Created a cluster with `k3k create`: 
```
k3kcli cluster create --namespace shared --mode shared --servers 1 sharedcluster
```
- create a pod with downward api
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: downward-api-limits
  name: downward-api-limits
spec:
  containers:
  - command:
    - sh
    - -c
    - env
    env:
    - name: CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.cpu
    - name: MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.memory
    image: registry.k8s.io/e2e-test-images/busybox:1.36.1-1
    imagePullPolicy: IfNotPresent
    name: dapi-container
```

- get the logs of the pod
```
kubectl logs downward-api-limits
```

**Expected behavior:**

you should see the following in the logs:
```
....
CPU_LIMIT=6
....
MEMORY_LIMIT=12243832832
```
**Actual behavior:**
CPU_LIMIT and MEMORY_LIMIT variable are empty
