### ISSUE TITLE
Priority classes are not being synced to the host cluster

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#340]
**Environmental Info:**
Host Cluster Version: 

v1.32.3+k3s1
Node(s) CPU architecture, OS, and Version: 

1 node ubuntu 24.04

Host Cluster Configuration:

1 server

K3K Cluster Configuration:

1 server shared mode

**Describe the bug:**

Priorityclasses are not being synced to the host cluster and this causes the pods in shared mode to fail since it cant find the priorityclass it specified in the spec.

**Steps To Reproduce:**
- Created a cluster with `k3k create`: 
```
k3kcli cluster create --namespace shared --mode shared --servers 1 sharedcluster
```
- create a priority class
```
kubectl create priorityclass test
```
- create a pod that uses this priority class
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: pcpod
  name: pcpod
spec:
  priorityClassName: test
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: pc-container
```
**Expected Results:**

The pod to be created successfully

**Actual Results:**

The pod is failing to be created in the host cluster with this error:

```
pods "pcpod-default-sharedcluster-7063706f642b64656661756c742b7-b078f" is forbidden: no PriorityClass with name test was found
```
