### ISSUE TITLE
Failed to create a pod with custom DNS config

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#341]
**Environmental Info:**
Host Cluster Version: 

v1.32.3+k3s1
Node(s) CPU architecture, OS, and Version: 

1 node ubuntu 24.04

Host Cluster Configuration:

1 server

K3K Cluster Configuration:

1 server shared mode

**Describe the bug:**

Due to the nature of shared mode network injection, user will not be able to create a Pod with custom DNS config or a different DNS policy.

**Comment by ShylajaDevadiga** [comment]
### Validated fix using k3k version 0.3.2
```
k3kcli --version
k3kcli Version: v0.3.2
```
Created k3k cluster in shared mode on single node k3k cluster
```
k3kcli cluster create --namespace shared --mode shared --servers 1 sharedcluster
```
**Verified custom dns settings are working inside the testpod**
```
ec2-user@ip-172-31-16-141:~> cat custom-dns
apiVersion: v1
kind: Pod
metadata:
  name: custom-dns
  namespace: kube-system
spec:
  containers:
  - name: dnsmasq
    image: jpillora/dnsmasq
    ports:
    - containerPort: 53
      protocol: UDP
    args:
      - "-A"
      - "/custom.local/10.0.0.1"
      - "-A"
      - "/corp.internal/192.168.0.1"
```
**Updated testpod manifest with a custom dnsConfig**
```
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    foo2: bar2
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.42.0.16   # IP of your custom DNS pod
    searches:
      - svc.cluster.local
      - cluster.local
    options:
      - name: ndots
        value: "2"
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: downward
      mountPath: /opt/annotations

```
**Validation results**
```
root@test-pod:/# nslookup data.custom.local
Server:		10.42.0.16
Address:	10.42.0.16#53

Name:	data.custom.local
Address: 10.0.0.1

root@test-pod:/# nslookup test.corp.internal
Server:		10.42.0.16
Address:	10.42.0.16#53

Name:	test.corp.internal
Address: 192.168.0.1
```
