### ISSUE TITLE
Pod stuck in CreateContainerConfigError after updating subpathexpr

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#345]
**Environmental Info:**
Host Cluster Version: 

v1.32.3+k3s1
Node(s) CPU architecture, OS, and Version: 

1 node ubuntu 24.04

Host Cluster Configuration:

1 server

K3K Cluster Configuration:

1 server shared mode

**Describe the bug:**

In shared mode when creating a pod with a missing subpathexpr, and then updating it, it will still be stuck in `CreateContainerConfigError`

**Steps To Reproduce:**
- Created a cluster with `k3k create`: 
```
k3kcli cluster create --namespace shared --mode shared --servers 1 sharedcluster
```
- create a a pod with subpathExpr
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    notmysubpath: mypath
  labels:
    name: var-expansion-test
  name: var-expansion-test
  namespace: default
spec:
  containers:
  - command:
    - sh
    - -c
    - tail -f /dev/null
    env:
    - name: POD_NAME
      value: foo
    - name: ANNOTATION
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['mysubpath']
    image: registry.k8s.io/e2e-test-images/busybox:1.36.1-1
    imagePullPolicy: IfNotPresent
    name: dapi-container
    volumeMounts:
    - mountPath: /subpath_mount
      name: workdir1
      subPathExpr: $(ANNOTATION)/$(POD_NAME)
    - mountPath: /volume_mount
      name: workdir1
  volumes:
  - emptyDir: {}
    name: workdir1
```

- After this pod is created it will be in createcontainerconfigerror as **expected** however after editing the pod and adding annotation
```
mysubpath: mypath
```
it will still be in error

**Expected behavior:**

The pod should be updated successfully

**Actual behavior:**

Failure

**Additional context / logs:**
