### ISSUE TITLE
Projected serviceaccounttokens volumes are not being handled in shared mode

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3k#348]
**Environmental Info:**
Host Cluster Version: 

v1.32.3+k3s1
Node(s) CPU architecture, OS, and Version: 

1 node ubuntu 24.04

Host Cluster Configuration:

1 server

K3K Cluster Configuration:

1 server shared mode

**Describe the bug:**

In shared mode we transform volumes from virtual cluster to host cluster that includes:
- secrets
- configmaps
- projected configmaps
- projected secrets

However projected serviceaccounttokens are not being handled correctly, this causing the failure of the following conformance test as well

```
 [FAIL] [sig-auth] ServiceAccounts [It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance] [sig-auth, Conformance]
  k8s.io/kubernetes/test/e2e/auth/service_accounts.go:666
```

**Comment by galal-hussein** [comment]
## Validation Template

Context: https://github.com/rancher/k3k/pull/660

## Root Cause

Projected service account tokens were not translated in shared mode, this issue caused a known failure in conformance tests

## What was fixed, or what change have occurred

k3k-kubelet now handles translation of projected service account tokens, when creating a pod with projected service account volume, then it should be picked up and translated successfully:

## Areas or cases that should be tested

### Case 1

1. Create a shared k3k cluster
2. Create a pod that uses projected service account token:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: nginx
    name: test-pod
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: sa-token
      readOnly: true
  volumes:
  - name: sa-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: test-audiance
          expirationSeconds: 600
          path: sa-token
```

3. pod shoud be created correctly and the projected token has succefully translated on the host cluster

```
kubectl get secrets -n shared-x k3k-default-test-audiance-600-sa-token-default-shar-e9925 -o json 
{
    "apiVersion": "v1",
    "data": {
        "sa-token": "ZXlKa...."
    },
    "kind": "Secret",
    "metadata": {
        "annotations": {
            "k3k.io/name": "k3k-default-oidc-discovery-test-600-sa-token",
            "k3k.io/namespace": "default"
        },
        "creationTimestamp": "2026-04-16T19:26:51Z",
        "labels": {
            "k3k.io/clusterName": "sharedcluster"
        },
        "name": "k3k-default-oidc-discovery-test-600-sa-token-default-shar-e9925",
        "namespace": "shared-x",
        "resourceVersion": "23252",
        "uid": "5c073d1c-ec18-4c60-a958-1a5f75da955e"
    },
    "type": "Opaque"
}
```
