### ISSUE TITLE
`ClusterSet` -> `VirtualClusterPolicy` RFD update

### ISSUE THREAD

**Issue by enrichman** [rancher/k3k#360]
After the RFD approval we need to update a bit the current implementation.

First of all the original `ClusterSet` _namespaced_ resource is now a _cluster_ scoped resource, called `VirtualClusterPolicy`. A policy can be applied to one or more Namespace with an annotation. When a Namespace is bound then the policy applies.

## Acceptance tests

The PR was touching many parts of the original ClusterSet implementation. If some not blocking issues are found it's probably better to open a new issue.

#### Create policy 

`k3kcli policy create NAME` should create a policy with the default values.

#### Delete policy 

`k3kcli policy delete NAME` should delete a policy with the default values.

## Namespace resources

When a policy is created _and bound to a namespace_ some resources in the namespace are created, depending on the spec.

**Important:** a Namespace can be bound to a policy setting a label `policy.k3k.io/policy-name` with the `<POLICY_NAME>`:

Note: you can easily create/update a resource with `kubectl apply` and heredoc:

```
cat <<EOF | kubectl apply -f -
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: simple
EOF
```

An empty policy is created with just the `allowedMode` defaulted to `shared`

### `allowedMode`

This field restricts the ability to deploy/provision virtual clusters in a different mode than the one specified.

```
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: simple
spec:
  allowedMode: shared
```

This flag can also be specified via the cli: `k3kcli policy create --mode virtual mypol`

When a Cluster is created with a non allowed mode then it should show an error in its status. Note that the resources are still created, but this behavior is not yet implemented (tracked via #310 or #350).

### `quota`

When the `quota` field is specified, the same [ResourceQuota](https://kubernetes.io/docs/concepts/policy/resource-quotas/) in the Namespace is created:

```
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: simple
spec:
  quota:
    hard:
      cpu: "10"
      memory: "20Gi"
      pods: "10"
```

### `limit`

When the `limit` field is specified, the same [LimitRange](https://kubernetes.io/docs/concepts/policy/limit-range/) in the Namespace is created:

```
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: simple
spec:
  limit:
    limits:
    - default:
        cpu: 500m
      defaultRequest:
        cpu: 500m
      max:
        cpu: "1"
      min:
        cpu: 100m
      type: Container
```

### `disableNetworkPolicy`

When the `disableNetworkPolicy` field is set to `true`, the NetworkPolicy to restrict the networking will NOT be created. By default this NetworkPolicy exists.

```
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: simple
spec:
  disableNetworkPolicy: true
```

### `podSecurityAdmissionLevel`

With the `podSecurityAdmissionLevel` it's possible to specify a PSA level. It will add the proper labels to the Namespace. The level must be one of `privileged`, `baseline`, or `restricted`.

```
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: simple
spec:
  podSecurityAdmissionLevel: baseline
```

**Comment by ShylajaDevadiga** [comment]
@enrichman I am seeing an error while creating VirtualClusterPolicy with the resource not found under api version k3k.io/v1alpha1 while using k3kcli Version: v0.3.3-rc1. Is there any pre-requisites before installing the policy?
```
ec2-user@ip-172-31-22-244:~> kubectl get nodes
NAME                                          STATUS   ROLES                       AGE   VERSION
ip-172-31-22-244.us-east-2.compute.internal   Ready    control-plane,etcd,master   21m   v1.33.1+rke2r1
ip-172-31-24-255.us-east-2.compute.internal   Ready    <none>                      19m   v1.33.1+rke2r1
ec2-user@ip-172-31-22-244:~> kubectl get crd virtualclusterpolicies.k3k.io
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "virtualclusterpolicies.k3k.io" not found
ec2-user@ip-172-31-22-244:~> kubectl get nodes
NAME                                          STATUS   ROLES                       AGE   VERSION
ip-172-31-22-244.us-east-2.compute.internal   Ready    control-plane,etcd,master   30m   v1.33.1+rke2r1
ip-172-31-24-255.us-east-2.compute.internal   Ready    <none>                      28m   v1.33.1+rke2r1
ec2-user@ip-172-31-22-244:~> kubectl get pods -A|grep k3k
k3k-system    k3k-647f5bf64f-kxpjq                                                   1/1     Running     0             16m
ec2-user@ip-172-31-22-244:~> k3kcli --version
k3kcli Version: v0.3.3-rc1
ec2-user@ip-172-31-22-244:~> k3kcli policy create policy1
INFO[0000] Creating policy [policy1]                    
FATA[0000] no matches for kind "VirtualClusterPolicy" in version "k3k.io/v1alpha1" 
ec2-user@ip-172-31-22-244:~> 
```

**Comment by enrichman** [comment]
Hi @ShylajaDevadiga , did you install the latest available version, with the `--devel` flag? It should be the `0.3.3-r1`.

**Comment by enrichman** [comment]
Hi @ShylajaDevadiga, awesome! So, let's go step by step.

A policy is bound to a **Namespace**.

> Important: a Namespace can be bound to a policy setting a label policy.k3k.io/policy-name with the <POLICY_NAME>:

So the Virtual Clusters needs to be created in the **same namespace** the policy is bound to. This can be done in different ways.

You can either create the clusters with the `--namespace` flag, like you did, and the label manually the namespace.

```
k3kcli policy create policy1
k3kcli cluster create --namespace shared --mode shared k3kcluster
kubectl label namespace shared --overwrite "policy.k3k.io/policy-name=policy1"
```

Or you can specify the policy during the creation, and it will also label the namespace for you.

```
k3kcli policy create policy1
k3kcli cluster create --namespace shared --policy policy1 --mode shared k3kcluster
```

Checking the code I think there could be a couple of bugs/improvements around this. It could fail for already existing namespace, or adding the second cluster (?).


Be aware that as stated in the description the "failure" is not yet implemented:

> When a Cluster is created with a non allowed mode then it should show an error in its status. Note that the resources are still created, but this behavior is not yet implemented (tracked via https://github.com/rancher/k3k/issues/310 or https://github.com/rancher/k3k/issues/350).

So you should be able to create the two clusters. This is something that we need to do for GA, or maybe if we feel this to have a very high priority we can push it for the next rease at the end of the month (/cc @jp-gouin)

**Comment by enrichman** [comment]
Thanks @ShylajaDevadiga, I was having a look at your commands and I probably spotted the issue.

You have bound the VirtualClusterPolicy **policy1** to the test1 namespace:
```
kubectl describe ns test1
Name:         test1
Labels:       kubernetes.io/metadata.name=test1
              policy.k3k.io/policy-name=policy1
Annotations:  <none>
Status:       Active

No resource quota.

No LimitRange resource.
```

but then you created _another_ policy called **test1**, with the quota:

```
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: test1
spec:
  quota:
    hard:
      cpu: "10"
      memory: "20Gi"
      pods: "10"
```

and you have not bound this policy to the namespace. You can check this even before trying to create many server or pods, just listing the ResourceQuotas in the namespace.

**Comment by ShylajaDevadiga** [comment]
Validated policy with quota with pod count set to 10, does not allow more than 10 pods to be created in the ns
```
ec2-user@ip-172-31-24-11:~> cat policy2
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: policy2
spec:
  quota:
    hard:
      pods: "10"
```
Note: coredns is on pending state
```
ec2-user@ip-172-31-24-11:~> kubectl get pods -A|grep test2
test2                coredns-697968c856-4cfgk-kube-system-k3kcluster4-636f7265-2a399       0/1     Pending     0            2m49s
test2                coredns-697968c856-9mcq6-kube-system-k3kcluster3-636f7265-79e5e       1/1     Running     0            5m8s
test2                coredns-697968c856-fw6n7-kube-system-k3kcluster2-636f7265-eddf4       1/1     Running     0            4m8s
test2                k3k-k3kcluster2-kubelet-ldp9d                                         1/1     Running     0            5m43s
test2                k3k-k3kcluster2-server-0                                              1/1     Running     0            5m42s
test2                k3k-k3kcluster3-kubelet-8pg62                                         1/1     Running     0            6m44s
test2                k3k-k3kcluster3-server-0                                              1/1     Running     0            6m44s
test2                k3k-k3kcluster4-kubelet-9vr4b                                         1/1     Running     0            4m23s
test2                k3k-k3kcluster4-server-0                                              1/1     Running     0            4m23s
test2                k3k-k3kcluster5-server-0                                              1/1     Running     0            2m27s
```
Validated limitRange with max cpu limit set to 1 and request to 2 cpus
```
ec2-user@ip-172-31-24-11:~> cat policy3
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: test2
spec:
  limit:
    limits:
    - default:
        cpu: 500m
      defaultRequest:
        cpu: 500m
      max:
        cpu: "1"
      min:
        cpu: 100m
      type: Container
ec2-user@ip-172-31-24-11:~> cat limitpod
apiVersion: v1
kind: Pod
metadata:
  name: test-over-limit
  namespace: test2
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "2"

```
When we have multiple resources set in quota, cluster creation fails
```
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: policy2
spec:
  quota:
    hard:
      cpu: "10"
      memory: "20Gi"
      pods: "10"
```
```
k3kcli cluster create --namespace test2 --mode shared  --policy policy2 k3kcluster2
INFO[0000] Creating namespace [test2]                   
INFO[0000] Creating cluster [k3kcluster2] in namespace [test2] 
INFO[0000] Extracting Kubeconfig for [k3kcluster2] cluster 
INFO[0000] waiting for cluster to be available..        
FATA[0120] secrets "k3k-k3kcluster2-bootstrap" not found 
```
With pvc in pending state
```
ec2-user@ip-172-31-24-11:~> kubectl get pv,pvc -A
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                             STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/pvc-826c3239-a488-46da-b688-53c51b23dbbf   1G         RWO            Delete           Bound    test1/varlibrancherk3s-k3k-k3kcluster1-server-0   local-path     <unset>                          7h26m
persistentvolume/pvc-a3c73df0-78c6-4b12-a790-799a8dae47a1   1G         RWO            Delete           Bound    shared/varlibrancherk3s-k3k-k3kcluster-server-0   local-path     <unset>                          7h28m

NAMESPACE   NAME                                                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
shared      persistentvolumeclaim/varlibrancherk3s-k3k-k3kcluster-server-0    Bound     pvc-a3c73df0-78c6-4b12-a790-799a8dae47a1   1G         RWO            local-path     <unset>                 7h30m
test1       persistentvolumeclaim/varlibrancherk3s-k3k-k3kcluster1-server-0   Bound     pvc-826c3239-a488-46da-b688-53c51b23dbbf   1G         RWO            local-path     <unset>                 7h26m
test2       persistentvolumeclaim/varlibrancherk3s-k3k-k3kcluster2-server-0   Pending                                                                        local-path     <unset>                 7m12s

```
Reason cpu limit is not set
```
test2       14m         Warning   FailedCreate              daemonset/k3k-k3kcluster2-kubelet                                 Error creating: pods "k3k-k3kcluster2-kubelet-tx8xd" is forbidden: failed quota: k3k-policy2: must specify cpu for: k3k-k3kcluster2-kubelet; memory for: k3k-k3kcluster2-kubelet
test2       3m48s       Warning   FailedCreate              daemonset/k3k-k3kcluster2-kubelet                                 (combined from similar events): Error creating: pods "k3k-k3kcluster2-kubelet-p4wnr" is forbidden: failed quota: k3k-policy2: must specify cpu for: k3k-k3kcluster2-kubelet; memory for: k3k-k3kcluster2-kubelet
test2       14m         Normal    SuccessfulCreate          statefulset/k3k-k3kcluster2-server                                create Claim varlibrancherk3s-k3k-k3kcluster2-server-0 Pod k3k-k3kcluster2-server-0 in StatefulSet k3k-k3kcluster2-server success
test2       3m47s       Warning   FailedCreate              statefulset/k3k-k3kcluster2-server                                create Pod k3k-k3kcluster2-server-0 in StatefulSet k3k-k3kcluster2-server failed error: pods "k3k-k3kcluster2-server-0" is forbidden: failed quota: k3k-policy2: must specify cpu for: k3k-k3kcluster2-server; memory for: k3k-k3kcluster2-server
test2       4m29s       Normal    WaitForFirstConsumer      persistentvolumeclaim/varlibrancherk3s-k3k-k3kcluster2-server-0   waiting for first consumer to be created before binding

```
Issue for track the requirement to create vcp with limit set https://github.com/rancher/k3k/issues/383

Modify the policy above to include disableNetworkPolicy: true and re-apply
cat policy2.yaml
```
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: policy2
spec:
  disableNetworkPolicy: true
```
```
kubectl apply -f policy2.yaml
networkpolicy.networking.k8s.io/deny-all created
```
As expected networkpolicy for test2 ns does not exist and pod to pod communication is successful
```
kubectl get networkpolicy -A
NAMESPACE   NAME             POD-SELECTOR   AGE
shared      k3k-k3kcluster   <none>         15h
test1       k3k-policy1      <none>         15h
```
```
ec2-user@ip-172-31-24-11:~>kubectl get pod nginx -n test2 nginx -o wide
ec2-user@ip-172-31-24-11:~>kubectl get pods -A -o wide |grep nginx
```

```
ec2-user@ip-172-31-24-11:~>kubectl run curl --image=curlimages/curl -it --restart=Never --rm -n test2 -- /bin/sh

$ curl http://10.42.0.43
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
```
Edit test2 ns and remove the disableNetworkPolicy policy above, expecting default NetworkPolicy with be re-created
```
kubectl edit ns test2
```
default NetworkPolicy is not re-created, thus still returning page content
```
ec2-user@ip-172-31-24-11:~> kubectl get networkpolicy -A
NAMESPACE   NAME             POD-SELECTOR   AGE
shared      k3k-k3kcluster   <none>         16h
test1       k3k-policy1      <none>         15h
```
```
kubectl run curl1 --image=curlimages/curl -it --restart=Never --rm -n test2 -- /bin/sh
If you don't see a command prompt, try pressing enter.
~ $ curl http://10.42.0.43
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>

```
Delete k3k-controller
```
ec2-user@ip-172-31-24-11:~> kubectl get pod -n k3k-system 
NAME                  READY   STATUS    RESTARTS   AGE
k3k-6889f4d47-44c2t   1/1     Running   0          16h
ec2-user@ip-172-31-24-11:~> kubectl delete pod -n k3k-system k3k-6889f4d47-44c2t
pod "k3k-6889f4d47-44c2t" deleted
```
```
kubectl run curl1 --image=curlimages/curl -it --restart=Never --rm -n test2 -- /bin/sh
If you don't see a command prompt, try pressing enter.
~ $ curl http://10.42.0.43
^C
```

```
ec2-user@ip-172-31-24-11:~> kubectl get networkpolicy -A
NAMESPACE   NAME              POD-SELECTOR   AGE
shared      k3k-k3kcluster    <none>         16h
test1       k3k-policy1       <none>         15h
test2       k3k-k3kcluster2   <none>         2s
test2       k3k-k3kcluster3   <none>         1s
test2       k3k-k3kcluster4   <none>         7s
test2       k3k-k3kcluster5   <none>         6s
```
Issue to track need to re-create k3k-controller to reflect the changes in ns https://github.com/rancher/k3k/issues/384

**Comment by ShylajaDevadiga** [comment]
Validated above issue here https://github.com/rancher/k3k/issues/384#issuecomment-3007118415
### Validated podSecurityAdmissionLevel policy
**podSecurityAdmissionLevel: baseline**
```
ec2-user@ip-172-31-28-87:~> cat policy3
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: policy3
spec:
  podSecurityAdmissionLevel: baseline
```
```
ec2-user@ip-172-31-28-87:~> k3kcli policy list
NAME      MODE
policy2   shared
policy3   shared
ec2-user@ip-172-31-28-87:~> kubectl describe ns test2
Name:         test2
Labels:       kubernetes.io/metadata.name=test2
              pod-security.kubernetes.io/enforce=baseline
              pod-security.kubernetes.io/enforce-version=latest
              pod-security.kubernetes.io/warn=baseline
              pod-security.kubernetes.io/warn-version=latest
              policy.k3k.io/policy-name=policy3
Annotations:  <none>
Status:       Active

No resource quota.

No LimitRange resource.
ec2-user@ip-172-31-28-87:~> 
```
```
cat privileged-pod
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: test2
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true
```
```
kubectl apply -f privileged-pod
Error from server (Forbidden): error when creating "p-pod": pods "privileged-pod" is forbidden: violates PodSecurity "baseline:latest": privileged (container "nginx" must not set securityContext.privileged=true)
```
**podSecurityAdmissionLevel: restricted**
```
ec2-user@ip-172-31-28-87:~> cat policy3
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: policy3
spec:
  podSecurityAdmissionLevel: restricted
```
```
ec2-user@ip-172-31-28-87:~> cat restricted-pod
apiVersion: v1
kind: Pod
metadata:
  name: restricted-fail-pod
  namespace: test2
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      runAsUser: 0
```
```
ec2-user@ip-172-31-28-87:~> kubectl apply -f restricted-pod 
Error from server (Forbidden): error when creating "restricted-pod": pods "restricted-fail-pod" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx" must set securityContext.runAsNonRoot=true), runAsUser=0 (container "nginx" must not set runAsUser=0), seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

```
**podSecurityAdmissionLevel: privileged,** test pod fails under baseline or restricted
```
ec2-user@ip-172-31-28-87:~> cat privileged-pod
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: test2
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true
```
```
ec2-user@ip-172-31-28-87:~> cat policy3
apiVersion: k3k.io/v1alpha1
kind: VirtualClusterPolicy
metadata:
  name: policy3
spec:
  podSecurityAdmissionLevel: privileged
```
```
ec2-user@ip-172-31-28-87:~> kubectl apply -f policy3
virtualclusterpolicy.k3k.io/policy3 configured
ec2-user@ip-172-31-28-87:~> kubectl apply -f privileged-pod 
pod/privileged-pod created
```
```
ec2-user@ip-172-31-28-87:~> cat privileged-pod
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: test2
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true

ec2-user@ip-172-31-28-87:~> kubectl get pods -A |grep pri
test2                privileged-pod                                                        1/1     Running     0               23s
ec2-user@ip-172-31-28-87:~> 

```
