### ISSUE TITLE
Kubeconfig secret

### ISSUE THREAD

**Issue by jp-gouin** [rancher/k3k#402]
**Environmental Info:**
Host Cluster Version: 
 RKE2 v1.31.5+rke2r1 

Host Cluster Configuration:
1 node cluster
K3k-0.3.3-rc5

K3K Cluster Configuration:
1 server `shared` mode virtual cluster with `NodePort` exposition

**Describe the bug:**
The generated Kubeconfig uses the `NodePort` value but uses the `ip` of the `service` and not the `ExternalIP` of the nodes

**Steps To Reproduce:**
- Created a cluster with `k3kcli cluster create mycluster`: 

**Expected behavior:**
A secret named `k3k-mycluster-kubeconfig` is created. 
This `kubeconfig` should use the internal `service` with port `443` regardless of the expose method choosen.
The user will made the appropriate changes in the `kubeconfig`  (similar to RKE2 and K3s approach)

**Actual behavior:**
Server URL of the `kubeconfig`  is mixed with the `serviceIP` and the `NodePort` which is not working.

**Comment by mdrahman-suse** [comment]
@jp-gouin I am seeing that the kubeconfig has the service IP but not the port `443`... is this expected?

Decode kubeconfig secret
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTlRVNE56TTRORGt3SGhjTk1qVXdPREl5TVRRME5EQTVXaGNOTXpVd09ESXdNVFEwTkRBNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTlRVNE56TTRORGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRaURIakdSMFRXVTFJY0NCVTR6b0sxazQ3bE0rR1U5OGQ4aGNHL0ErMjAKSVcrc0RRenEzQzFGYUxDSkNTTzA1U0hZeTdjWVZjT1gzcGUvZC9ISTJ5d1JvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVFmdWRWRUVGQkpLUlZZWjM5N2FxClVweXlwSmN3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU5zWDJ2NVgveFFjWnhTTytmeWlkTWlZTU5OdUF2RkoKREthY085elE0d05iQWlFQTNQenZjTkZFQ3l1S2diazFnR0psRjZzZHRPSXJjZVpUU0lLS3RzdDgvWXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://10.43.21.46
  name: default
...
```
