### ISSUE TITLE
k3k not working on AKS cluster 1.27.7

### ISSUE THREAD

**Issue by xinity** [rancher/k3k#94]
i've been trying k3k on my AKS cluster:
```
OS: linux (amd64)
OS Image: Ubuntu 22.04.4 LTS
Kernel version: 5.15.0-1056-azure
Container runtime: containerd://1.7.7-1
Kubelet version: v1.27.7
```

tried this yaml : 
```
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: single-server
spec:
  servers: 1
  agents: 3
  token: test
  version: v1.26.0-k3s2
  clusterCIDR: 10.30.0.0/16
  serviceCIDR: 10.31.0.0/16
  clusterDNS: 10.31.0.10
  serverArgs:
  - "--write-kubeconfig-mode=777"
  expose:
    ingress:
      enabled: true
      ingressClassName: "nginx"
```

the deployment fails because the readiness probe fails ( 127.0.0.1:6443 connection refused)

full log available here: https://pastebin.com/me8fhV8q

any hints on what's happening perhaps ? :)
